(function(){"use strict";var form=document.getElementById("cotacao");if(!form)return;var nota=document.getElementById("formNota");var botao=form.querySelector("button[type=submit]");var enviando=false;var q=new URLSearchParams(window.location.search);["origem","destino","carga"].forEach(function(nome){var v=q.get(nome);if(v&&form.elements[nome]&&!form.elements[nome].value){form.elements[nome].value=v;}});function valor(nome){var el=form.elements[nome];return el&&el.value?el.value.trim():"";}
function avisar(texto){if(nota)nota.textContent=texto;if(nota)nota.classList.remove("ruim");}
function avisarErro(texto){if(nota){nota.textContent=texto;nota.classList.add("ruim");}}
function mostrarSucesso(protocolo,titulo){if(nota)nota.textContent="";var antigo=form.querySelector(".form-ok");if(antigo)antigo.parentNode.removeChild(antigo);var caixa=document.createElement("div");caixa.className="form-ok";caixa.setAttribute("role","status");caixa.setAttribute("tabindex","-1");var h=document.createElement("p");h.className="form-ok-titulo";h.textContent=titulo;caixa.appendChild(h);if(protocolo){var pr=document.createElement("p");pr.className="form-ok-proto";pr.appendChild(document.createTextNode("Seu protocolo"));var b=document.createElement("b");b.textContent=protocolo;pr.appendChild(b);caixa.appendChild(pr);}
var n=document.createElement("p");n.className="form-ok-nota";n.textContent="Enviamos uma confirmação para o seu e-mail. Guarde o protocolo: com ele a gente acha a "+"conversa sem você repetir tudo.";caixa.appendChild(n);form.appendChild(caixa);if(caixa.scrollIntoView)caixa.scrollIntoView({block:"center"});if(caixa.focus)caixa.focus();}
function emailPlausivel(v){var i=v.indexOf("@");if(i<1||/\s/.test(v))return false;var dominio=v.slice(i+1);return dominio.indexOf(".")>0&&dominio.lastIndexOf(".")<dominio.length-1;}
var ROTULO={nome:"o nome",email:"o e-mail",mensagem:"os dados da carga",telefone:"o telefone",};function focar(campo){var el=form.elements[campo];if(el&&el.focus)el.focus();}
form.addEventListener("submit",function(ev){ev.preventDefault();if(enviando)return;if(valor("empresa")){avisar("Cotação enviada. Em breve entramos em contato.");return;}
var obrigatorios=["origem","destino","carga","nome","email"];for(var i=0;i<obrigatorios.length;i++){if(!valor(obrigatorios[i])){avisarErro("Preencha os campos obrigatórios (*).");var campo=form.elements[obrigatorios[i]];if(campo&&campo.focus)campo.focus();return;}}
if(!emailPlausivel(valor("email"))){avisarErro("Confira o e-mail: ele precisa ter @ e um domínio, como nome@empresa.com.br.");focar("email");return;}
var linhas=["Origem: "+valor("origem"),"Destino: "+valor("destino"),"Carga: "+valor("carga"),"Peso: "+(valor("peso")||"-"),"Coleta: "+(valor("quando")||"-"),];var extra=valor("mensagem");if(extra)linhas.push("","Mensagem:",extra);var pedidoDeRota=q.get("pedido")==="rota";var corpo={nome:valor("nome"),email:valor("email"),mensagem:linhas.join("\n"),assunto:"comercial",perfil:"embarcador",origem:pedidoDeRota?"rota-solicitada":"cotacao",};if(valor("telefone"))corpo.telefone=valor("telefone");enviando=true;if(botao)botao.disabled=true;avisar("Enviando…");fetch("/api/contato",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(corpo),}).then(function(r){if(r.status===422){return r.json().then(function(d){var erro=new Error("validacao");erro.validacao=d&&d.detail;throw erro;});}
if(!r.ok)throw new Error("http "+r.status);return r.json();}).then(function(dados){form.reset();mostrarSucesso(dados&&dados.protocolo,"Recebemos sua cotação.");}).catch(function(erro){var det=erro&&erro.validacao;if(det&&det.length){var campo=det[0].loc&&det[0].loc[1];avisarErro("Confira "+(ROTULO[campo]||"os dados")+" e envie de novo.");if(campo)focar(campo);return;}
avisarErro("Não consegui enviar agora. Tente de novo em instantes ou escreva para contato@nexfert.com.br.");}).then(function(){enviando=false;if(botao)botao.disabled=false;});});})();